# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    #runs-on: ubuntu-latest
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/github-script@v3
        id: set-result
        with:
          script: return "Hello!"
          result-encoding: string
      - name: Get result
        #run: "& {C:\Users\Administrator\Downloads\CxConsolePlugin-2021.1.1\runCxConsole.cmd asyncscan -v -cxserver http://checkmarkx.redshift.local -projectname CxServer\WebGoat-7.0.1 -CxToken 7a83a8f102349b0531745f81af133b99567a8827c2cb9930e3100edf7247dc9e -locationtype folder -locationpath C:\Checkmarx\CxFlow\actions-runner\actions-runner-win-x64-2.277.1\_work\WebGoat\WebGoat}"
        #run: cmd /c "powershell.exe C:\\Checkmarx\\CxUtils\\Redshift\\runScan.ps1"
        #run: echo "${{steps.set-result.outputs.result}}"
        run: C:\actions-runner\ps_script.ps1

